// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACJMhlHGLzUAYaV7a3D_nbgHPV_Xvg1kI',
    appId: '1:311228428876:web:a7fbf64772bad9d2547ae9',
    messagingSenderId: '311228428876',
    projectId: 'mr-mikes-students',
    authDomain: 'mr-mikes-students.firebaseapp.com',
    storageBucket: 'mr-mikes-students.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARDoWYmUvIREccvtu66UJ4rexRqgQMwHQ',
    appId: '1:311228428876:android:83b38485c9bef1ac547ae9',
    messagingSenderId: '311228428876',
    projectId: 'mr-mikes-students',
    storageBucket: 'mr-mikes-students.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuHIW4XzWYkbgFJ0-3ZxBOiEJfrC2E9M0',
    appId: '1:311228428876:ios:8ba7a387ed8a1314547ae9',
    messagingSenderId: '311228428876',
    projectId: 'mr-mikes-students',
    storageBucket: 'mr-mikes-students.appspot.com',
    iosBundleId: 'com.example.mrMikesStudents',
  );
}
